# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c0e6495560524a7efeac1af9ff10065"
application_url = "https://example.com"
embedded = true
name = "Surprise discount"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,read_orders"

[shop.metafields.app.surprise_discount_settings]
type = "json"
name = "Surprise Discount Storefront Settings"
description = "Configuration managed from the Surprise Discount admin dashboard"

  [shop.metafields.app.surprise_discount_settings.access]
  admin = "merchant_read_write"

[webhooks]
api_version = "2026-07"
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
