api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "surprise-discount-function"
type = "function"
uid = "6f9f8ba0-0d3c-b0c8-4b82-d2a7cb768484687899c8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
